version: '3.4'
 
services:
  web:
    container_name: featurebasedweb
    image: ${DOCKER_REGISTRY-}web
    ports:
        - "5000:5000"
        - "5001:5001"
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=clean.db,1433;Database=cleanarchitecturedb;User Id=SA;Password=SuperPassword123;TrustServerCertificate=True;"
    depends_on:
       clean.db:
        condition: service_healthy
    networks:
        - feature-based-network
 
  clean.db:
    container_name: featurebasedwebdb
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=SuperPassword123
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
    networks:
        - feature-based-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "SuperPassword123" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
 
  clientweb:
    image: node:latest
    container_name: client.web
    build:
      context: ./src/Web/ClientApp
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "44447:44447"
    volumes:
      - ./src/Web/ClientApp:/app
      - /app/node_modules
      - ./src/Web/ClientApp/.env.development:/app/.env.development
 
networks:
  feature-based-network: